config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/about' => 'homes#about'
  root to: 'homes#top'
  devise_for :users
  
  # 簡単ログイン機能実装
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  # 簡単ログイン機能ここまで
  get 'follows_books' => 'users#follows_book'
  resources :users, only: [:index, :show, :edit, :create, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #通知機能
  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  
  default_scope->{order(create_at: :desc)}
  
  belongs_to :book, optional: true
  belongs_to :post_comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true 
  # トーク機能への通知↓
  belongs_to :room, optional: true
  belongs_to :chat, optional: true
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  
  def index
    #ログインユーザーへの通知を全て代入(自身で自身の投稿にいいねした通知は)
    @notifications = current_user.passive_notifications.where.not(visitor_id: current_user.id)
    #whereで未読の通知のみに絞る？ブロック変数に代入してeach処理
    @notifications.where(checked: false).each do |notification|
      #未読通知をchecked: trueにすることで既読にしている?
      notification.update_attributes(checked: true)
    end
  end
  
  def destroy_all
    #表示されている全ての通知を削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
  
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
  #checked: false(未確認通知)の有無を判定するメソッド定義(今回はheaderのボタンでのif文で使用)
  def unchecked_notifications
    #未確認の通知を全て代入
    notifications=current_user.passive_notifications.where(checked: false)
    # 未読の全通知から自身の投稿に対する自身のコメントやいいねは除外して代入
    @notifications = notifications.where.not(visitor_id: current_user.id)
  end
  # _notification.html.erbで使用するhelperメソッドを定義
  def notification_form(notification)
    @comment=nil
    visitor=link_to notification.visitor.name, notification.visitor, style:"font-weight: bold;"
    #本の投稿がないユーザーだとbook.titleがnilになってエラーになるので条件分岐（オリジナル）
    unless notification.book.nil?
      your_post=link_to notification.book.title, book_path(notification.book), style:"font-weight: bold;"
    end
    case notification.action
      when "follow" then
        "#{visitor}があなたをフォローしました"
      when "favorite" then
        "#{visitor}が#{your_post}にいいね！しました"
      when "comment" then
        @comment=PostComment.find_by(id:notification.post_comment_id)
        "#{visitor}が#{your_post}にコメントしました"
      when "dm" then
        "#{visitor}からDMが届いています"
    end
  end
  
end

app/views/notifications/_notification.html.erb
<!--個別のインスタンスを、notificationとして部分テンプレートで使用できる-->
<% visitor=notification.visitor %>
<% post=notification.book %>

<div class="user-view clearfix ">
  <%= link_to user_path(notification.visitor) do %>
    <%=  attachment_image_tag notification.visitor, :profile_image, :fill, 30, 30, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'30x30'%>
  <% end %>
  <%== notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
  <br>
  
</div>

app/views/notifications/index.html.erb
<div>
  <h4 class="sub-title">通知</h4>
    <%= link_to destroy_all_notifications_path, method: :delete do %>
      <i class="fas fa-trash" style="color: black;"></i>
      <h7 style="color: black;">全削除</h7>
    <% end %>
  <% if @notifications.exists? %>
    <div class="users-index">
      <!--インスタンスの数だけ、部分テンプレートnotifications/_notification.html.erbが呼び出される-->
      <%= render @notifications %>

    </div>
  <% else %>
    <p>通知はありません</p>
  <% end %>
</div>