config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/about' => 'homes#about'
  root to: 'homes#top'
  devise_for :users
  
  # 簡単ログイン機能実装
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  # 簡単ログイン機能ここまで
  get 'follows_books' => 'users#follows_book'
  resources :users, only: [:index, :show, :edit, :create, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #通知機能
  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  
  attachment :profile_image
  
  # フォロー機能↓
  # 自分がフォローしてるユーザとの関連
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # 自分がフォローされてるユーザーとの関連
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  
  # 通知機能↓
  has_many :active_notifications, class_name: "Notification", foreign_key: :visitor_id, dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: :visited_id, dependent: :destroy
  # 通知機能ここまで
  
  # トーク機能
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  
  # フォロー機能↓
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @users = User.all
    @user = current_user
    @post_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @post_book = Book.new
    @books = Book.all
    @favorite_books = @user.favorite_books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User was successfully updated."
      redirect_to user_path(@user)
    else
      # @users = User.all
      render :edit
    end
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
  
  def search
    if params[:name].present?
      @users = User.where('name LIKE ?', "%#{params[:name]}%")
    else
      @users = User.none
    end
  end
  
  def follows_book
     @follows_books = Book.where(user_id: [current_user.id, *current_user.following_ids])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
    <h2>User info</h2>
    
    <%= form_with model:@user, local: true do |f| %>
    <div class="field">
        <label for="user_name">Name</label>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <label for="user_profile_image">Image</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    </div>
    <div class="field">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction %>
    </div>
    <div class="actions">
         <%= f.submit "Update User" %>
    </div>
    <% end %>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="col-xs-6">
  <h1>followers</h1>

  <table class="table table-hover table-inverse">
    <thead>
      <th class="title">name</th> 
      <th class="title">introduction</th>
      <th class="title">follow</th>
    </thead>
      <% @users.each do |user| %>
    <tbody>
      <th>
        <p><%= link_to user.name, user_path(user.id) %></p>
      </th>
      <th>
        <p><%= user.introduction %></p>
      </th>
      <th>
        <% if current_user != user %>
          <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn-anfollow btn-sm btn-default" %></p>
          <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-follow btn-sm btn-default" %></p>
          <% end %>
        <% end %>
      </th>
    </tbody>
      <% end %>
  </table>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="col-xs-6">
  <h1>follows</h1>

  <table class="table table-hover table-inverse">
    <thead>
      <th class="title">name</th> 
      <th class="title">introduction</th>
      <th class="title">follow</th>
    </thead>
      <% @users.each do |user| %>
    <tbody>
      <th>
        <p><%= link_to user.name, user_path(user.id) %></p>
      </th>
      <th>
        <p><%= user.introduction %></p>
      </th>
      <th>
        <% if current_user != user %>
          <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn-anfollow btn-sm btn-default" %></p>
          <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-follow btn-sm btn-default" %></p>
          <% end %>
        <% end %>
      </th>
    </tbody>
      <% end %>
  </table>
  
  </div>
</div>

app/views/users/follows_book.html.erb
  <div>
    <% @follows_books.each do |book| %>
      <%= book.title %>
    <% end %>
  </div>

app/views/users/foolows_book.js.erb
$('.ajax-exercise<%= current_user.id %>').html("<%= j(redirect_to 'users/follows_books', locals: {@follows_books: @follows_books }) %>");

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2 class="glyphicon glyphicon-wrench">Userinfo</h2>
      <p>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'100x100'%>
      </p>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th class="title">name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th class="title">introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
      <% if @user == current_user %>
        <%= link_to edit_user_path(@user) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% else %>
        <%= link_to user_path(current_user.id) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% end %>
      </div>
      <!--部分テンプレ-->
      <h2 class="glyphicon glyphicon-book">NewBook</h2>
      <%= form_with model: @post_book, local: true do |f| %>
      <div class="field-row">
        <label for="book_title title">Title</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="field-row">
        <label for="book_body title">Opinion</label>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="actions row">
        <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
      </div>
      <% end %>
      <!--ここまで-->
    </div>
    <div class="col-xs-9">
      <span>
        <spam>
          <h2 class="glyphicon glyphicon-user">Users</h2>
          
        </spam>
        <!--Gemなし検索機能-->
        <spam>
          <%= link_to "User seach", search_users_path, class:"btn btn-default" %>
        </spam>
        <!--Gemなしここまで-->
        
      </span>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th class="title">image</th>
            <th class="title">name</th>
            <th>Show</th>
            <th>follo</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <th>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'40x40'%>
            </th>
            <th><%= user.name %></th>
            <th>
              <%= link_to "Show", user_path(user) %>
            </th>
            <th>
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                  <p><%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn-anfollow btn-sm btn-default" %></p>
                <% else %>
                  <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-follow btn-sm btn-default" %></p>
                <% end %>
              <% end %>
            </th>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<!--Gemなし検索機能-->

<div class="container">
  <div class="col-xs-6">
    <h1>User search</h1>
    <%= form_with url:search_users_path, method: :get, local: true do |f| %>
      <%= f.text_field :name %>
      <%= f.submit :search %>
    <% end %>
    <table>
      <thead>
        <tr>Name</tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <tb><%= user.name %></tb>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="col-xs-6">
    <h1>郵便番号から住所検索</h1> 
    <label>郵便番号
      <input type="text" id="postcode" maxlength="8" placeholder="例:0000000">
    </label>
    <button id="btn">検索</button>
    <div id="result">
      <h2>検索結果</h2>
      <p><label>都道府県
        <input type="text" id="pref" size="6">
      </label></p>
      <p><label>市区町村
        <input type="text" id="city">
      </label></p>
      <p><label>住所
        <input type="text" id="address">
      </label></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2 class="glyphicon glyphicon-wrench">Userinfo</h2>
      <p class="slidedown">
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'100x100'%>
      </p>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th class="title">name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th class="title">introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        
      <!--チャットへのlink-->
      <% if current_user != @user %>
        <%= link_to 'チャットする', chat_path(@user.id) %>
      <% end %>  
        
      <% if @user == current_user %>
        <%= link_to edit_user_path(@user) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% else %>
        <%= link_to user_path(current_user.id) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% end %>
      </div>
      <!--部分テンプレ-->
      <h2 class="glyphicon glyphicon-book">NewBook</h2>
      <%= form_with model: @post_book, local: true do |f| %>
      <div class="field-row">
        <label for="book_title title">Title</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="field-row title">
        <label for="book_body">Opinion</label>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="actions row">
        <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
      </div>
      <% end %>
      <!--ここまで-->
    </div>
    <div class="col-xs-9">
      <h2 class="glyphicon glyphicon-home">Home</h2>
      
      <hr>
      <div class="follow">
        <span>
          <spam><%=link_to "フォロー", follows_user_path(@user.id), class: "btn-sm btn-default"  %></spam>
          <spam><%=link_to "フォロワー", followers_user_path(@user.id), class: "btn-sm btn-default" %></spam>
          <spam class="ajax-exercise<%= current_user.id %>"><%= link_to "フォローユーザーの投稿", follows_books_path, remote: true, class: "btn-sm btn-default" %></spam>
          <spam>
            <% if current_user != @user %>
              <% if @user.followed_by?(current_user) %>
                <%=link_to "フォロー解除", user_relationships_path(@user.id), method: :delete, class: "btn-anfollow btn-sm btn-default" %>
              <% else %>
                <%=link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn-follow btn-sm btn-default" %>
              <% end %>
            <% end %>
          </spam>
        </span>
      </div>  
      <hr>
      <div class="col-xs-8">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>Image</th>
              <th class="title">Title</th>
              <th class="title">Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
            <% @user.books.each do |book| %>
            <tbody>
              <tr>
                <th class="slidedown">
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'40x40'%>
                <% end %>
                </th>
                <th class="slidedown"><%= link_to book.title, book_path(book.id) %></th>
                <th class="slidedown"><%= book.body %></th>
              </tr>
            </tbody>
            <% end %>
        </table>
       </div>
   
    <!--いいね数表示-->
        <div class="dropdown col-xs-4">
          <button class="glyphicon glyphicon-book btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">いいねした投稿
            <span class="caret"></span>
          </button>
            <ul class="dropdown-menu">
              <% @favorite_books.each do |book| %>
                <li><%= link_to book.title, book_path(book.id) %></li>
              <% end %>
            </ul>
        </div>
    <!--いいね表示ここまで-->
    
    </div>
  </div>
</div>  　　