config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/about' => 'homes#about'
  root to: 'homes#top'
  devise_for :users
  
  # 簡単ログイン機能実装
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  # 簡単ログイン機能ここまで
  get 'follows_books' => 'users#follows_book'
  resources :users, only: [:index, :show, :edit, :create, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #通知機能
  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :notifications, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
# いいねに対する通知↓
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      book_id: id,
      visited_id: user_id,
      action: "favorite"
    )
    notification.save if notification.valid?
  end
# ここまでいいね通知
  
#ここからコメントへの通知
  def create_notification_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(book_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
        save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      book_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
#ここまでコメント通知

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @books = Book.all
    @post_book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @post_book = Book.new
    @post_comment = PostComment.new
    @favorite_users = @book.favorite_users
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def create
    @post_book = Book.new(book_params)
    @post_book.user_id = current_user.id
    if @post_book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@post_book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def update
    @book =  Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "User was successfully updated."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with model:@book, local: true do |f| %>
        <div class="field row">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"col-xs-12" %>
        </div>
        <div class="field row">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class:"col-xs-12" %>
        </div>
        <div class="actions row">
        <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
        </div>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2 class="glyphicon glyphicon-wrench ">Userinfo</h2>
      <p>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'100x100'%>
      </P>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th class="title">name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th class="title">introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
      <% if @user == current_user %>
        <%= link_to edit_user_path(@user) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% else %>
        <%= link_to user_path(current_user.id) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% end %>
      </div>
      <!--部分テンプレ-->
      <h2 class="glyphicon glyphicon-book">NewBook</h2>
      <%= form_with model: @post_book, local: true do |f| %>
      <div class="field-row">
        <label for="book_title title">Title</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="field-row">
        <label for="book_body title">Opinion</label>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="actions row">
        <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
      </div>
      <% end %>
      <!--ここまで-->
    </div>
    <div class="col-xs-9">
      <h2 class="glyphicon glyphicon-book">Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th class="title">Title</th>
            <th class="title">Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <th>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'40x40'%>
            <% end %>
            </th>
            <th><%= link_to book.title, book_path(book.id) %></th>
            <th><%= book.body %></th>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2 class="glyphicon glyphicon-wrench">Userinfo</h2>
      <p>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'100x100'%>
      </p>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th class="title">name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th class="title">introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      
      <div class="row">
      <% if @user == current_user %>
        <%= link_to edit_user_path(@user) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% else %>
        <%= link_to user_path(current_user.id) do %>
          <i class="glyphicon glyphicon-wrench col-xs-12 btn btn-default info"></i>
        <% end %>
      <% end %>
      </div>
      <!--部分テンプレ-->
      <h2 class="glyphicon glyphicon-book">NewBook</h2>
      <%= form_with model: @post_book, local: true do |f| %>
      <div class="field-row">
        <label for="book_title title">Title</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="field-row">
        <label for="book_body title">Opinion</label>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="actions row">
        <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
      </div>
      <% end %>
      <!--ここまで-->
    </div>
    <div class="col-xs-9">
      <h2 class="glyphicon glyphicon-book">Bookdetail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th class="title">Title</th>
            <th class="title">Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
            <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, class: "attachment user profile_image fallback img-circle avatar", fallback: "no_image.jpg", size:'40x40'%>
            <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <td>
            <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy", book_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-danger" %>
            <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      
      <div class="dispray">
        
        <!--いいね機能-->
        <div id="likes_buttons_<%= @book.id %>">
          <%= render partial: 'favorites/favorite', locals: { book: @book} %>
        </div>
        <!--↑Ajaxの場合の_favoliteファイルの呼び出し-->
        
        <!--いいねここまで-->
        
        
        <!--ここからフォロー機能-->
        
        <div class="follo">
          <% if current_user != @book.user %>
            <% if @book.user.followed_by?(current_user) %>
              <p><%= link_to "フォロー解除", user_relationships_path(@book.user.id), method: :delete, class: "btn-anfollow btn-sm btn-default" %></p>
            <% else %>
              <p><%= link_to "フォローする", user_relationships_path(@book.user.id), method: :post, class: "btn-follow btn-sm btn-default" %></p>
            <% end %>
          <% end %>
        </div>
      </div>  
        <!--ここまでフォロー-->
  

      <!--コメント機能render-->
      <div id="comments_area_<%= @book.id %>">
        <%= render partial: 'post_comments/index', locals: { book: @book } %>
      </div>
      <%= render partial: 'post_comments/form', locals: { book: @book, post_comment: @post_comment } %>
      <!--コメントここまで-->
      
      <!--いいねのリスト-->
      <div class="dropdown">
        <div class="col-xs-4">
          <button class="glyphicon glyphicon-user btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">いいねした人
            <span class="caret"></span>
          </button>
            <ul class="dropdown-menu">
              <% @favorite_users.each do |user| %>
                <li><%= link_to user.name, user_path(user.id) %></li>
              <% end %>
            </ul>
        </div>
      </div>
      <!--いいねリストここまで-->
    </div>
  </div>
</div>