config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/about' => 'homes#about'
  root to: 'homes#top'
  devise_for :users
  
  # 簡単ログイン機能実装
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  # 簡単ログイン機能ここまで
  get 'follows_books' => 'users#follows_book'
  resources :users, only: [:index, :show, :edit, :create, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #通知機能
  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newbookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/32c3e3eeaa.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span style="color: white; font-size: 40px; color: #fa051b">B</span>
          <span style="color: white; font-size: 40px; color: #faa319">o</span>
          <span style="color: white; font-size: 40px; color: #fdf65e">o</span>
          <span style="color: white; font-size: 40px; color: #c7fd5e">k</span>
          <span style="color: white; font-size: 40px; color: #62fd5e">e</span>
          <span style="color: white; font-size: 40px; color: #5efde1">r</span>
          <span style="color: white; font-size: 40px; color: #5e7bfd">s</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) do %>
                <i class="glyphicon glyphicon-home"></i>  Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                <i class="glyphicon glyphicon-user"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path do %>
                <i class="glyphicon glyphicon-book"></i> Books
                <% end %>
              </li>
              
              <li>
                <!--if文の中のメソッドはヘルパーで定義、新規通知の有無で光点を表示-->
                <%= link_to notifications_path do %> NOTICE
                  <% if unchecked_notifications.any? %>
                    <i class="fa fa-circle notification-circle", style="color: gold;"><%= @notifications.count %></i>
                  <% end %>
                <% end %>
              </li>
              
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="glyphicon glyphicon-log-out"></i> logout
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path do %>
                <i class="glyphicon glyphicon-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path do %>
                <i class="glyphicon glyphicon-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path do %>
                <i class="glyphicon glyphicon-edit"></i> sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                <i class="glyphicon glyphicon-log-in"></i> login
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="body">

      <%= yield %>

    </div>
    <footer>
      <div class="container footer">
        <div class="row">
          <div class="col-xs3 col-xs-offset-9">
            <p style="color: white; margin: 10px 0;">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>